Update patch set 1
Patch Set 1:

Danesh, this is working?

frameworks/base/../../external/libphonenumber/java/src/com/android/i18n/phonenumbers/PhoneNumberUtil.java:19: package android.text does not exist
import android.text.TextUtils;
                   ^
frameworks/base/../../external/libphonenumber/java/src/com/android/i18n/phonenumbers/PhoneNumberUtil.java:2574: cannot find symbol
symbol  : variable TextUtils
location: class com.android.i18n.phonenumbers.PhoneNumberUtil
      if (TextUtils.isEmpty(number)) {

Patch-set: 1
Reviewer: Jorge Ruesga <3134@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0